" tabs, basic options
set ts=4 sw=4
set ruler
set showmatch
set expandtab
set shiftwidth=4
" vim-airline
set laststatus=2
set ttimeoutlen=50
" vim-syntastic
let g:syntastic_mode_map = {"mode": "passive"}
let g:syntastic_python_checkers = ['flake8']
let g:syntastic_c_checkers = ['cppcheck']
let g:syntastic_cpp_checkers = ['cppcheck']
let g:syntastic_always_populate_loc_list = 1
"let g:syntastic_auto_loc_list = 1
let g:syntastic_check_on_open = 1
let g:syntastic_check_on_wq = 0
